# LoginStreaks Database Configuration
# Set enabled to true to use MySQL database for streak tracking

database:
  enabled: false
  host: localhost
  port: 3306
  name: minecraft
  username: root
  password: password
  useSSL: false

# Connection pool settings (optional)
connection:
  maxPoolSize: 10
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
