name: LoginStreaks
main: com.osmc.loginstreaks.LoginStreaks
version: 1.0
description: loginstreaks gives money for every day you log in
author: ItsVollx

commands:
  loginstreak:
    description: Check your login streak status
    usage: /<command> [help|top|<player>]
    aliases: [ls, streak]
  loginstreakadmin:
    description: Admin commands for managing login streaks
    usage: /<command> <set|reset|reload> [player] [amount]
    aliases: [lsa, streakadmin]
    permission: loginstreaks.admin

permissions:
  loginstreaks.admin:
    description: Allows access to admin commands
    default: op
